#!/usr/bin/env python3
"""Generate client stubs, server dispatch and the entry-point table.

    python3 codegen/emit.py --api codegen/api.json

Reads the model from parse.py, applies annotations.py, and writes:

    common/generated/api_ids.h        stable ids and names
    client/generated/client_stubs.cpp one definition per driver function
    client/generated/proc_table.inc   name -> pointer, for cuGetProcAddress
    server/generated/dispatch.cpp     the matching server side

Any function we cannot marshal gets a stub that logs its name and returns
CUDA_ERROR_NOT_SUPPORTED, so a gap shows up as a loud failure rather than a
wrong answer. That log is the worklist for filling the API out.
"""

import argparse
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import annotations as ann  # noqa: E402

HEADER = """// Generated by codegen/emit.py. Do not edit.
// Regenerate with ./codegen/run.sh
"""

# Annotations that take a size expression, e.g. in_buffer(ByteCount).
_SIZED = re.compile(r"^(in_buffer|out_buffer)\(([^)]*)\)$")


class Unmarshalable(Exception):
    """Raised when a parameter has no representation we can generate."""


def plan_param(p, annotation):
    """Decide how one parameter travels. Annotation wins over classification."""
    if annotation:
        m = _SIZED.match(annotation)
        if m:
            return {"mode": m.group(1), "size": m.group(2)}
        if annotation in ("pod_in", "pod_out", "fatbin", "ignore"):
            return {"mode": annotation}
        if annotation in ("out_scalar", "scalar", "handle", "string"):
            return {"mode": annotation}
        raise Unmarshalable("unknown annotation %r" % annotation)

    kind = p["kind"]
    if kind == "unknown":
        raise Unmarshalable(p["detail"] or "unclassified")
    return {"mode": kind}


def plan_function(f):
    a = ann.for_function(f["name"])
    plans = []
    for p in f["params"]:
        plans.append(plan_param(p, a["params"].get(p["name"])))
    return plans, a


def decl_params(f):
    """Reconstruct the C parameter list exactly as declared."""
    if not f["params"]:
        return "void"
    out = []
    for p in f["params"]:
        t = p["type"]
        if "[" in t or "(" in t:
            # Array or function-pointer syntax needs the name spliced inside
            # the type; we do not generate those, so refuse early.
            raise Unmarshalable("undeclarable type %r" % t)
        sep = "" if t.endswith("*") else " "
        out.append("%s%s%s" % (t, sep, p["name"]))
    return ", ".join(out)


# --------------------------------------------------------------------------
# client side
# --------------------------------------------------------------------------

def emit_client_request(p, plan):
    """Fields the client writes into the request, in parameter order."""
    n, m = p["name"], plan["mode"]
    L = []
    if m == "scalar":
        L.append("  req.put<%s>(%s);" % (p["type"], n))
    elif m == "handle":
        L.append("  req.put<uint64_t>(reinterpret_cast<uint64_t>(%s));" % n)
    elif m == "string":
        L.append("  req.put_str(%s);" % n)
    elif m in ("out_scalar", "out_handle", "pod_out"):
        L.append("  req.put<uint8_t>(%s ? 1 : 0);" % n)
    elif m == "pod_in":
        L.append("  req.put<uint8_t>(%s ? 1 : 0);" % n)
        L.append("  if (%s) req.put_bytes(%s, sizeof(*%s));" % (n, n, n))
    elif m == "in_buffer":
        L.append("  req.put<uint8_t>(%s ? 1 : 0);" % n)
        L.append("  if (%s) req.put_sized(%s, (size_t)(%s));"
                 % (n, n, plan["size"]))
    elif m == "out_buffer":
        L.append("  req.put<uint8_t>(%s ? 1 : 0);" % n)
        L.append("  req.put<uint64_t>((uint64_t)(%s));" % plan["size"])
    elif m == "fatbin":
        # The API gives no length; the image describes its own size.
        L.append("  req.put<uint8_t>(%s ? 1 : 0);" % n)
        L.append("  if (%s) req.put_sized(%s, rgpu::image_size(%s));"
                 % (n, n, n))
    elif m == "ignore":
        pass
    else:
        raise Unmarshalable(m)
    return L


def emit_client_response(p, plan):
    """Fields the client reads back out of the response."""
    n, m = p["name"], plan["mode"]
    L = []
    if m == "out_scalar":
        L.append("  if (%s && !rsp.get(%s)) return CUDA_ERROR_UNKNOWN;" % (n, n))
    elif m == "out_handle":
        L.append("  if (%s) { uint64_t h_; if (!rsp.get(&h_)) return CUDA_ERROR_UNKNOWN;" % n)
        L.append("            *%s = reinterpret_cast<%s>(h_); }" % (n, p["pointee"]))
    elif m == "pod_out":
        L.append("  if (%s) { const uint8_t* b_; size_t n_;" % n)
        L.append("            if (!rsp.get_sized(&b_, &n_) || n_ != sizeof(*%s)) return CUDA_ERROR_UNKNOWN;" % n)
        L.append("            memcpy(%s, b_, n_); }" % n)
    elif m == "out_buffer":
        L.append("  if (%s) { const uint8_t* b_; size_t n_;" % n)
        L.append("            if (!rsp.get_sized(&b_, &n_)) return CUDA_ERROR_UNKNOWN;")
        L.append("            memcpy(%s, b_, n_); }" % n)
    return L


def emit_client_stub(f, plans, a):
    name = f["name"]
    lines = ["extern \"C\" CUresult %s(%s) {" % (name, decl_params(f))]
    lines.append("  rgpu::Buffer req;")
    for p, plan in zip(f["params"], plans):
        lines += emit_client_request(p, plan)
    lines.append("  rgpu::Buffer rsp;")
    lines.append("  CUresult r_ = rgpu::call(rgpu::API_%s, req, &rsp);" % name)
    lines.append("  if (r_ != CUDA_SUCCESS) return r_;")
    for p, plan in zip(f["params"], plans):
        lines += emit_client_response(p, plan)
    lines.append("  return r_;")
    lines.append("}")
    return lines


def emit_fake_driver(f):
    """A weak, do-nothing definition of a real driver entry point.

    Linking these into the server lets the whole stack run with no GPU: real
    client stubs, real wire format, real server dispatch. Weak linkage lets
    tests/fake_cuda.cpp override the handful that need to behave.
    """
    return ["extern \"C\" __attribute__((weak)) CUresult %s(%s) {"
            % (f["name"], decl_params(f)),
            "  return CUDA_ERROR_NOT_SUPPORTED;",
            "}"]


def emit_client_unsupported(f, why):
    return ["extern \"C\" CUresult %s(%s) {" % (f["name"], decl_params(f)),
            "  return rgpu::unimplemented(\"%s\", \"%s\");" % (f["name"], why),
            "}"]


# --------------------------------------------------------------------------
# server side
# --------------------------------------------------------------------------

def emit_server_case(f, plans):
    name = f["name"]
    L = ["case rgpu::API_%s: {" % name]
    args = []
    post = []
    for p, plan in zip(f["params"], plans):
        n, m = p["name"], plan["mode"]
        v = "v_" + n
        if m == "scalar":
            L.append("  %s %s{}; if (!req.get(&%s)) return CUDA_ERROR_INVALID_VALUE;"
                     % (p["type"], v, v))
            args.append(v)
        elif m == "handle":
            L.append("  uint64_t u_%s{}; if (!req.get(&u_%s)) return CUDA_ERROR_INVALID_VALUE;" % (n, n))
            L.append("  %s %s = reinterpret_cast<%s>(u_%s);" % (p["type"], v, p["type"], n))
            args.append(v)
        elif m == "string":
            L.append("  std::string s_%s; bool has_%s=false;" % (n, n))
            L.append("  if (!req.get_str(&s_%s, &has_%s)) return CUDA_ERROR_INVALID_VALUE;" % (n, n))
            args.append("has_%s ? s_%s.c_str() : nullptr" % (n, n))
        elif m in ("out_scalar", "out_handle"):
            ctype = p["pointee"]
            L.append("  uint8_t has_%s{}; if (!req.get(&has_%s)) return CUDA_ERROR_INVALID_VALUE;" % (n, n))
            L.append("  %s %s{};" % (ctype, v))
            args.append("has_%s ? &%s : nullptr" % (n, v))
            if m == "out_scalar":
                post.append("  if (has_%s) rsp->put(%s);" % (n, v))
            else:
                post.append("  if (has_%s) rsp->put<uint64_t>(reinterpret_cast<uint64_t>(%s));" % (n, v))
        elif m in ("pod_in", "pod_out"):
            ctype = p["pointee"]
            L.append("  uint8_t has_%s{}; if (!req.get(&has_%s)) return CUDA_ERROR_INVALID_VALUE;" % (n, n))
            L.append("  %s %s{};" % (ctype, v))
            if m == "pod_in":
                L.append("  if (has_%s) { const uint8_t* b_; if (!req.get_bytes(sizeof(%s), &b_)) return CUDA_ERROR_INVALID_VALUE; memcpy(&%s, b_, sizeof(%s)); }"
                         % (n, v, v, v))
            else:
                post.append("  if (has_%s) rsp->put_sized(&%s, sizeof(%s));" % (n, v, v))
            args.append("has_%s ? &%s : nullptr" % (n, v))
        elif m in ("in_buffer", "fatbin"):
            L.append("  uint8_t has_%s{}; if (!req.get(&has_%s)) return CUDA_ERROR_INVALID_VALUE;" % (n, n))
            L.append("  const uint8_t* b_%s = nullptr; size_t n_%s = 0;" % (n, n))
            L.append("  if (has_%s && !req.get_sized(&b_%s, &n_%s)) return CUDA_ERROR_INVALID_VALUE;" % (n, n, n))
            args.append("has_%s ? (%s)b_%s : nullptr" % (n, p["type"], n))
        elif m == "out_buffer":
            L.append("  uint8_t has_%s{}; uint64_t n_%s{};" % (n, n))
            L.append("  if (!req.get(&has_%s) || !req.get(&n_%s)) return CUDA_ERROR_INVALID_VALUE;" % (n, n))
            L.append("  std::vector<uint8_t> b_%s(has_%s ? n_%s : 0);" % (n, n, n))
            args.append("has_%s ? (%s)b_%s.data() : nullptr" % (n, p["type"], n))
            post.append("  if (has_%s) rsp->put_sized(b_%s.data(), b_%s.size());" % (n, n, n))
        elif m == "ignore":
            args.append("nullptr")
        else:
            raise Unmarshalable(m)

    L.append("  CUresult r_ = ::%s(%s);" % (name, ", ".join(args)))
    # Outputs are only meaningful on success, but CUDA fills some of them even
    # on failure; sending them back unconditionally keeps client and server in
    # lockstep on the response layout.
    L += post
    L.append("  return r_;")
    L.append("}")
    return L


# --------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--api", default="codegen/api.json")
    ap.add_argument("--root", default=".")
    a = ap.parse_args()

    with open(a.api) as f:
        doc = json.load(f)
    funcs = doc["functions"]
    aliases = doc.get("aliases", {})

    for d in ("common/generated", "client/generated", "server/generated",
              "tests/generated"):
        os.makedirs(os.path.join(a.root, d), exist_ok=True)

    generated, manual, stubbed = [], [], []
    absent = []  # cannot even be declared, so no symbol is exported
    client_body, server_body, fake_body = [], [], []

    # Every entry point the server might reference gets a weak fake, so the
    # GPU-free build links.
    for f in funcs:
        try:
            fake_body += emit_fake_driver(f) + [""]
        except Unmarshalable:
            pass

    for f in funcs:
        name = f["name"]
        if name in ann.HANDWRITTEN:
            manual.append(name)
            continue
        why = ann.UNSUPPORTED.get(name)
        if why:
            stubbed.append((name, why))
            try:
                client_body += emit_client_unsupported(f, why) + [""]
            except Unmarshalable:
                absent.append(name)
            continue
        try:
            plans, meta = plan_function(f)
            stub = emit_client_stub(f, plans, meta)
            case = emit_server_case(f, plans)
        except Unmarshalable as e:
            stubbed.append((name, str(e)))
            try:
                client_body += emit_client_unsupported(f, str(e)) + [""]
            except Unmarshalable:
                absent.append(name)  # no symbol exported for this one
            continue
        generated.append(name)
        client_body += stub + [""]
        server_body += ["  " + l for l in case] + [""]

    all_names = sorted(generated + manual + [n for n, _ in stubbed])

    # --- api_ids.h --------------------------------------------------------
    ids = [HEADER, "#pragma once", "#include <cstdint>", "",
           "namespace rgpu {", "enum ApiId : uint32_t {"]
    for i, n in enumerate(all_names):
        ids.append("  API_%s = %d," % (n, i + 1))
    ids += ["  API__count = %d," % (len(all_names) + 1), "};", "",
            "// Name for logging. Returns \"?\" for an unknown id.",
            "const char* api_name(uint32_t id);", "}  // namespace rgpu", ""]
    write(a.root, "common/generated/api_ids.h", ids)

    names_cc = [HEADER, "#include \"common/generated/api_ids.h\"", "",
                "namespace rgpu {", "static const char* kNames[] = {\"?\","]
    names_cc += ["  \"%s\"," % n for n in all_names]
    names_cc += ["};",
                 "const char* api_name(uint32_t id) {",
                 "  return id < API__count ? kNames[id] : \"?\";",
                 "}", "}  // namespace rgpu", ""]
    write(a.root, "common/generated/api_names.cpp", names_cc)

    # --- client stubs -----------------------------------------------------
    cl = [HEADER, "#include <cstring>", "#include <cuda.h>", "",
          "#include \"client/rpc.h\"", "#include \"common/generated/api_ids.h\"",
          ""] + client_body
    write(a.root, "client/generated/client_stubs.cpp", cl)

    # --- entry point table ------------------------------------------------
    # cuGetProcAddress is asked for a base name plus a version, so the table
    # carries the alias names too: cuMemAlloc must resolve to cuMemAlloc_v2.
    defined = (set(generated) | set(manual) |
               {n for n, _ in stubbed}) - set(absent)
    entries = [(n, n) for n in all_names if n in defined]
    for base, target in sorted(aliases.items()):
        if target in defined and base not in defined:
            entries.append((base, target))
    tbl = [HEADER, "// Included by client/shim.cpp inside the entry table.",
           "// {name as requested, our implementation}"]
    for base, target in sorted(entries):
        tbl.append("RGPU_ENTRY(\"%s\", %s)" % (base, target))
    write(a.root, "client/generated/proc_table.inc", tbl)

    # --- fake driver, for the GPU-free integration test --------------------
    fk = [HEADER,
          "// Weak stand-ins for the real driver. tests/fake_cuda.cpp defines",
          "// strong versions of the few that need real behaviour.",
          "#include <cuda.h>", ""] + fake_body
    write(a.root, "tests/generated/fake_driver.cpp", fk)

    # --- server dispatch --------------------------------------------------
    sv = [HEADER, "#include <cstring>", "#include <string>", "#include <vector>",
          "#include <cuda.h>", "",
          "#include \"common/generated/api_ids.h\"", "#include \"common/wire.h\"",
          "",
          "namespace rgpu {",
          "// Returns true if `id` was handled. Hand-written handlers get first",
          "// refusal in the server, so anything reaching here is generated.",
          "bool dispatch_generated(uint32_t id, Buffer& req, Buffer* rsp,",
          "                        CUresult* out) {",
          "  switch (id) {"] + server_body + [
          "    default: return false;",
          "  }",
          "}",
          "}  // namespace rgpu", ""]
    # The generated cases `return` a CUresult; wrap them so the switch assigns.
    sv = fix_server_returns(sv)
    write(a.root, "server/generated/dispatch.cpp", sv)

    print("generated %d, hand-written %d, stubbed %d (%d undeclarable)"
          % (len(generated), len(manual), len(stubbed), len(absent)),
          file=sys.stderr)
    with open(os.path.join(a.root, "codegen/report.txt"), "w") as f:
        f.write("generated (%d):\n" % len(generated))
        for n in generated:
            f.write("  %s\n" % n)
        f.write("\nhand-written (%d):\n" % len(manual))
        for n in sorted(manual):
            f.write("  %s\n" % n)
        f.write("\nstubbed (%d):\n" % len(stubbed))
        for n, why in sorted(stubbed):
            f.write("  %-46s %s\n" % (n, why))


def fix_server_returns(lines):
    """Cases are emitted with `return r_;`; inside the switch they must assign
    to *out and report handled."""
    out = []
    for l in lines:
        if l.strip() == "return r_;":
            indent = l[:len(l) - len(l.lstrip())]
            out.append(indent + "*out = r_; return true;")
        elif "return CUDA_ERROR_INVALID_VALUE;" in l:
            # These guards sit mid-line after an `if (...)`, so match anywhere.
            # Returning the CUresult directly would convert it to bool and
            # leave *out unset, reporting the wrong error to the client.
            out.append(l.replace("return CUDA_ERROR_INVALID_VALUE;",
                                 "{ *out = CUDA_ERROR_INVALID_VALUE; return true; }"))
        else:
            out.append(l)
    return out


def write(root, path, lines):
    full = os.path.join(root, path)
    with open(full, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s" % path, file=sys.stderr)


if __name__ == "__main__":
    main()
